### ISSUE TITLE
DMV license doesnt load

### ISSUE THREAD

**Issue by BlueberryDonut** [HumanTree92/esx_licenseshop#1]
everything works perfectly except that the licenseshop wont detect that a player has a dmv license until i restart it in the cmd?

I dont know if its an issue i caused but is there code i can add into the dmvschool to update licenseshop when ever a dmv license is released?

**Comment by BlueberryDonut** [comment]
added 'ExecuteCommand("restart esx_licenseshop")' as a bandaid in my dmvschool theory success function.

**Comment by HumanTree92** [comment]
Sounds like to me you don't have it in a good load order. As this should be loaded after esx_dmvschool. But who knows what the real problem you are having. I have been running this with the default code with no problem. I have had over 5 people on my server and tested this without any licenses and still no issue. If the above works for you that is great.
