### ISSUE TITLE
Empty menu - buy license

### ISSUE THREAD

**Issue by FilexCZE** [HumanTree92/esx_licenseshop#10]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): v1 Final
Are you using Essentialmode?: No
Are you using ExtendedMode?: Yes
Are you using OneSync?: Yes
Linux or Windows?: Windows

I haved empty menu for buy license. I dont know why.

`Config.UseBlips = true -- true = Use License Shop Blips
Config.RequireDMV = false -- If true then it will require players to have Drivers Permit to buy other Licenses | false does the Opposite.
Config.AdvancedVehicleShop = true -- Set to true if using esx_advancedvehicleshop
Config.AdvancedWeaponShop = false -- Set to true if using esx_advancedweaponshop
Config.DMVSchool = false -- Set to true if using esx_dmvschool
Config.SellDMV = true -- Set to true if Config.RequireDMV = false & you want players to be able to buy Drivers Permit
Config.Drugs = false -- Set to true if using esx_drugs
Config.WeaponShop = false -- Set to true if using esx_weaponshop
`

DB:
![image](https://user-images.githubusercontent.com/75536352/113464534-ac4b7e80-942d-11eb-981e-e459468b3a18.png)

IN-GAME:
![image](https://user-images.githubusercontent.com/75536352/113464546-bf5e4e80-942d-11eb-9598-0d83c35f701c.png)

DB ME:
![image](https://user-images.githubusercontent.com/75536352/113464578-f46aa100-942d-11eb-972b-b63dedb4b858.png)

How i can fix it?

**Comment by HumanTree92** [comment]
https://github.com/HumanTree92/esx_licenseshop/blob/master/config.lua

**Comment by FilexCZE** [comment]
Reaction: config.lua is fix? ..i really know where is problem..

**Comment by HumanTree92** [comment]
Oh yeah where is it then

**Comment by FilexCZE** [comment]
I'm trying to understand, but I still can't find what's wrong. Do you think I have a true / false problem? But where?

**Comment by trclassic92** [comment]
There is currently nothing in mine either and I already edited my config.lua
