### ISSUE TITLE
 Nothing Showing Up

### ISSUE THREAD

**Issue by mifsopo** [HumanTree92/esx_licenseshop#11]
**Describe the Bug | A Clear & Concise Description of Bug**
it wasnt working before so ive reinstalled it , from the base (without editing anything) it still does not work 
i hit "E" it says buy a license. i hit enter and its empty only licesen i need is for weaponshop and even if i turn that to true it still doesnt work
**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  NO
Have you looked through the Closed Topics?: YES
Have you looked through the Wiki?: YES
Are you using a Pre-Installed ESX? If Yes who?: NO
Are you using es_extended? If Yes what Version? (Example: 1.2):  Yes Latest
Are you using Essentialmode?:  Yes
Are you using ExtendedMode?:  No
Are you using OneSync?:  No
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
Make sure you have edited the config.lua

**Comment by trclassic92** [comment]
I have changed my config.lua and non of my L's are showing up in the shop still....

**Comment by trclassic92** [comment]
https://i.imgur.com/ULEAwo6.png
