### ISSUE TITLE
No menu showing up when walking into license shop zone. 

### ISSUE THREAD

**Issue by TitanOptimus** [HumanTree92/esx_licenseshop#2]
This is the only error that im getting in the console. I've tried for a couple hours to remedy this..
Any help would be greatly appreciated. Also, do you know where the "weed license" gets imported to the database from? The licenseshop has no .sql file.  I have all required mods installed for the licenseshop.

Error resuming coroutine: @esx_licenseshop/client/main.lua:211: attempt to call a nil value (field 'ShowHelpNotification')
stack traceback:
@esx_licenseshop/client/main.lua:211: in function <@esx_licenseshop/client/main.lua:206>

**Comment by HumanTree92** [comment]
Weed license is from the esx_drugs. As far as line 211 which is ESX.ShowHelpNotification(CurrentActionMsg) you can just comment it out like --ESX.ShowHelpNotification(CurrentActionMsg)
