### ISSUE TITLE
esx_license/server/main.lia:93: attemnt to index a nil value (field '?')

### ISSUE THREAD

**Issue by Boffice** [HumanTree92/esx_licenseshop#4]
I get this error when i try to load the menu:
https://prnt.sc/rr8k6d

and here is my license table:
https://prnt.sc/rr8knv

**Comment by HumanTree92** [comment]
The error that you have provided is an error for esx_license & not this script which is called esx_licenseshop

**Comment by Boffice** [comment]
Sure but as mentioned above, i am getting this error when i try to interact with your NPC.
License Shop menu is empty and console sends above error.

reference to esx_license i have original one, unchanged:
https://github.com/ESX-Org/esx_license

**Comment by HumanTree92** [comment]
If the License Shop is empty you need to make sure this script is after esx_license. You also need to make sure you edit the Config to what you are using.

**Comment by Boffice** [comment]
1)esx_licenseshop is way after esx_license
2) I have set Config.AdvancedWeaponShop to true in config since this is the only resource i am using from the list.

Still getting the same error.

**Comment by Boffice** [comment]
Alright found the source of issue, user_licenses had record with invalid type i removed it and all works fine. 

Seems that store was checking my current licenses and that's why error was coming from esx_license.

Anyways you are amazing your resources are very useful, keep up the cool job!

**Comment by HumanTree92** [comment]
Thanks. Glad u found the problem.
