### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by prouargegamer** [HumanTree92/esx_licenseshop#6]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yea
Have you looked through the Wiki?: yea
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): yea 1.2
Are you using Essentialmode?: no
Are you using ExtendedMode?: yea
Are you using OneSync?: yea
Linux or Windows?: windows

@esx_licenseshop/server/main.lua:199: attempt to index a nil value (local 'xPlayer')

**Comment by HumanTree92** [comment]
This is a problem with Extendedmode not my script. The obvious is it can't find xPlayer which in my case i use es_extended V1 Final. You could try changing `local xPlayer = ESX.GetPlayerFromId(_source)` to `local xPlayer = ESX.GetPlayerFromId(source)`

**Comment by prouargegamer** [comment]
![20201121_132408](https://user-images.githubusercontent.com/73350738/99884549-142ac680-2bfd-11eb-95f4-c7eced286e32.jpg)

line 199
what to excatly write there?

**Comment by HumanTree92** [comment]
On line 197 change  `local xPlayer = ESX.GetPlayerFromId(_source)` to `local xPlayer = ESX.GetPlayerFromId(source)`

**Comment by HumanTree92** [comment]
If the above doesn't work then its something to do with ExtendedMode. As i don't have any issues like this on my end & im using es_extended V1 Final

**Comment by prouargegamer** [comment]
im using V1 Final too

**Comment by prouargegamer** [comment]
ok

**Comment by HumanTree92** [comment]
Well you did say that your using `Are you using ExtendedMode?: yea` So are you running both ExtendedMode & es_extended

**Comment by HumanTree92** [comment]
Also when you say `Are you using es_extended? If Yes what Version? (Example: 1.2): yea 1.2` this is what comes to my mind
[This is es_extended 1.2](https://github.com/esx-framework/es_extended/tree/1.2.0)
[This is es_extended V1 Final](https://github.com/esx-framework/es_extended/tree/v1-final)

**Comment by prouargegamer** [comment]
es_extended 1.2

**Comment by prouargegamer** [comment]
no extenededmode just esx_extended 1.2

**Comment by prouargegamer** [comment]
my finger keep slipping

**Comment by prouargegamer** [comment]
![20201121_134540](https://user-images.githubusercontent.com/73350738/99885009-fe6ad080-2bff-11eb-8897-5199b2ab75ab.jpg)

**Comment by HumanTree92** [comment]
If you using es_extended i would make sure that your using V1 Final. The V1 Final has the same fxmanifest.lua

**Comment by prouargegamer** [comment]
where is V1 Final?

**Comment by HumanTree92** [comment]
[This is es_extended V1 Final](https://github.com/esx-framework/es_extended/tree/v1-final)

**Comment by prouargegamer** [comment]
ok thanks ill try that one

**Comment by prouargegamer** [comment]
oh i tried that one before

**Comment by HumanTree92** [comment]
Yeah so my scripts only support es_extended V1 Final or Extendedmode. If you want this script to work with es_extended 1.2 then you would have to make the changes yourself.

**Comment by prouargegamer** [comment]
Alright

**Comment by prouargegamer** [comment]
thanks

**Comment by prouargegamer** [comment]
that worked thank you for your help

**Comment by prouargegamer** [comment]
![20201121_151647](https://user-images.githubusercontent.com/73350738/99886731-c1590b00-2c0c-11eb-9449-4ddbaca92502.jpg)

line 72 
do you know what might cause this error?
