### ISSUE TITLE
shop glitched

### ISSUE THREAD

**Issue by teramon1** [HumanTree92/esx_licenseshop#8]
**Describe the Bug | A Clear & Concise Description of Bug**
Welp pretty much when we go the the license shop it only shows aircraft? anyone know how to fix this.

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: nope
Have you looked through the Closed Topics?: yep
Have you looked through the Wiki?: yep
Are you using a Pre-Installed ESX? If Yes who?: nope did it all myself
Are you using es_extended? If Yes what Version? (Example: 1.2): nope
Are you using Essentialmode?: yep
Are you using ExtendedMode?: yep
Are you using OneSync?: yep
Linux or Windows?: windows

**Comment by teramon1** [comment]
sorry I don't think i fully explained like each license is there and working but there all labeled as aircraft.

**Comment by MitchellStierman** [comment]
I found the issue. Literally had the same issue yesterday as you and just had time to look into it. Open up your client\main.lua file and starting in the function labelled -- open license shop ALL licenses are set in the tabel.insert's (_u('license_aircraft')

If you open the locales\en.lua you can see the proper labels to put there for each weapon in place of the license_aircraft. 

Also, if you continue to scroll down to the "if Config.DMVSchool then" line, you will see that the DMV, drive_truck, drive and drive_bike licenses are all labeled as aircraft as well. Change these from en.lua as well and you are golden!

I again found it is the same story for the weed license and standard weapon license. If you keep scrolling down they are right after the DMVSchool. Change the same way again from en.lua

This line is just telling the menu to label them ALL as aircraft. Hope I explained that enough for you! I can't put in a change request so HumanTree92 will have to edit the code for new downloads to not have the issue.

**Comment by HumanTree92** [comment]
Fixed in ce37da748173940e36de746e6e67432be3f0e1ba
